# Generated by Django 3.1.7 on 2021-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowindata',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
